development:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: DE_train_03_development

test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: DE_train_03_production
